name: Races
author: joii_
version: 1.0
api-version: 1.19
main: com.joi.races.Main

depend: [PlaceholderAPI]

commands:
  races:
    usage: "Usage: /races"
    description: Open Races GUI.
  races set:
    usage: "Usage: /races set [race | tokens] <player> <value>"
    description: Set data for a player.
  races add:
    usage: "Usage: /races add tokens <player> <value>"
    description: Add to a player's tokens.
  races get:
    usage: "Usage: /races get [race | tokens] <player>"
    description: Get data for player.
  races list:
    usage: "Usage: /races list"
    description: Display a list of online players and their race.
  wings:
    usage: "Usage: /wings"
    description: Toggle wings on/off.