name: Races
author: joii_
version: 2
api-version: 1.19
main: com.joi.races.Main

depend: [PlaceholderAPI]

commands:
  races:
    usage: "Usage: /races"
    description: Open Races GUI.
  races set:
    usage: "Usage: /races set [race/tokens/color/head]"
    description: Set data for a race or player.
  races add:
    usage: "Usage: /races add [effect/tokens]"
    description: Add to effects or a player's tokens.
  races new:
    usage: "Usage: /races new [race] <name>"
    description: Add a new race.
  races remove:
    usage: "Usage: /races remove [race/effect]"
    description: Remove a race or effect.
  races get:
    usage: "Usage: /races get [race/tokens/effects]"
    description: Get info for a race or player.
  races list:
    usage: "Usage: /races list"
    description: Display a list of online players and their race.
  races wings:
    usage: "Usage: /races wings"
    description: Toggle fall damage on/off.
  races vision:
    usage: "Usage: /races vision"
    description: Toggle night vision on/off.
